### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wojsmol** [marocchino/on_artifact#476]
Is there a plan for a new release to address  https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. I see changes in `main` branch but stable release will be better.

**Comment by wojsmol** [comment]
@marocchino Any progress with this issue?

**Comment by marocchino** [comment]
Thank you for telling me. I just updated the dependencies, rebuild the project and tagged it.

**Comment by wojsmol** [comment]
@marocchino Can you create release forb last tag so it's more visible?

**Comment by marocchino** [comment]
done!
